### ISSUE TITLE
ABSENCES in your file structure

### ISSUE THREAD

**Issue by Imperatoras** [William-Yin1234/team_kocy__wyin10_ychan10_lkronman10_soh11#1]
Greetings Kocy,
It appears that ye have forgotten a few things of importance. Here is the required file structure as of 12/22:

app/
  __init__.py
  static/
      css/
  templates/
design.pdf
design_wiki.pdf
devlog.txt
flag.jpg
README.md
requirements.txt

some of these are missing :(

**Comment by Imperatoras** [comment]
(we are team Greedy Toads)

**Comment by William-Yin1234** [comment]
Created missing folders.
