### ISSUE TITLE
MISSING tables in database structure

### ISSUE THREAD

**Issue by Imperatoras** [William-Yin1234/team_kocy__wyin10_ychan10_lkronman10_soh11#2]
Hello again!
we would suggest that you put neat lil tables showing your table structure in your design doc, just cuz, and also some data types. Take a look at our design doc for inspiration! ;D
(shameless self promoooooo)

**Comment by Imperatoras** [comment]
(we are Greedy Toads)

**Comment by William-Yin1234** [comment]
Created tables
