### ISSUE TITLE
Clarify the component map

### ISSUE THREAD

**Issue by mhui10** [William-Yin1234/team_kocy__wyin10_ychan10_lkronman10_soh11#3]
In the component map, the arrows only go one way, (SQLite -> flask app -> HTML) but the flask app does have access to the sqlite database since you will be updating it with information. To clarify this further it would be nice if you could add arrows pointing both directions to better indicate the relation between the db and flask app.

**Comment by Stella-J-Oh** [comment]
Updated component map with suggestion
